language: r
warnings_are_errors: true
sudo: required
notifications:
  email:
    recipients:
      - reportmort@gmail.com
    on_success: change
    on_failure: always
env:
  global:
  - CRAN: http://cran.rstudio.com
  - NOT_CRAN: true
before_install:
- echo "options(repos = c(CRAN='https://cran.rstudio.com/'))" > ~/.Rprofile
- openssl aes-256-cbc -K $encrypted_fa943f9332f8_key -iv $encrypted_fa943f9332f8_iv -in tests/testthat/roas_setup.rds.enc -out tests/testthat/roas_setup.rds -d
r_github_packages:
- jimhester/covr
r_binary_packages:
- XML
- RCurl
- testthat
r_packages:
- rmarkdown
after_success:
- Rscript -e 'library(covr);codecov()'
  